services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
      - /var/lib/n8n:/var/lib/n8n:rw
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=n8n.proxy.shortcentral.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_EDITOR_BASE_URL=https://n8n.proxy.shortcentral.com
      - WEBHOOK_URL=https://n8n.proxy.shortcentral.com/
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_HOST=192.168.1.248
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_SCHEMA=n8n
      - DB_POSTGRESDB_PASSWORD=6523Tike

  clubspark-exporter:
    container_name: clubspark-exporter
    build:
      context: /root/clubspark-exporter
      dockerfile: Dockerfile
    image: local/clubspark-exporter:latest
    ports:
      - 3001:3001
    restart: unless-stopped

    environment:
      - PORT=3001
      - CLUBSPARK_EMAIL=steve@shortcentral.com
      - CLUBSPARK_PASSWORD=HQ#zo7P8C$
      - LTA_USERNAME=sshort
      - LTA_PASSWORD=fH8Urv2XrtZwXra!

  gotenberg:
    container_name: gotenberg
    image: gotenberg/gotenberg:8
    restart: unless-stopped
    ports:
      - 3002:3000

  n8n-mcp:
    image: mcp/n8n:latest
    container_name: n8n-mcp
    ports:
      - "3000:3000"
    environment:
      MCP_MODE: stdio
      AUTH_TOKEN: "VG72MN79FMoWeI1cvYWmuvPbGReQgfxD"
      N8N_BASE_URL: http://host.docker.internal:5678
      N8N_API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxYWEyNTY0NC1kMzg0LTQ4MTAtYmVhYS1mNTgzMTRkM2U3MGMiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzY4ODQwNjQwfQ.OztpaI1pkATZk8N9eB_oUvT7zaGN7YBtYRf6PmXRs3s
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 9443:9443
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data

  appsmith:
    container_name: appsmith
    image: index.docker.io/appsmith/appsmith-ee:latest
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - appsmith_data:/appsmith-stacks

volumes:
  n8n_data:
    external: true
    name: n8n_data
  portainer_data:
  appsmith_data:
