name: pangolin
services:

  cloudflare-ddns:
    environment:
      - API_KEY=CtVf87Rq-O7Bk3werF4gytbf4784tNdeXbEjctA3
      - ZONE=shortcentral.com
      - SUBDOMAIN=proxy
    image: oznu/cloudflare-ddns

  dockerproxysocket:
    image: tecnativa/docker-socket-proxy
    environment:
      - CONTAINERS=1 # Only allow reading container status
      - VERSION=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "2375:2375"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:2375/version"]
      interval: 30s
      timeout: 10s
      retries: 3

  pangolin:
    image: fosrl/pangolin:1.2.0
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/"]
      interval: "3s"
      timeout: "3s"
      retries: 5

  traefik:
    image: traefik:v3.3.3
    container_name: traefik
    restart: unless-stopped

    ports:
      - 443:443
      - 80:80

    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - ./config/traefik:/etc/traefik:ro # Volume to store the Traefik configuration
      - ./config/letsencrypt:/letsencrypt # Volume to store the Let's Encrypt certificates
      - ./config/traefik/logs:/var/log/traefik # Volume to store Traefik logs

networks:
  default:
    driver: bridge
    name: pangolin
