BEGIN;

CREATE TABLE IF NOT EXISTS public.raw_members_main_contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Venue ID" text,
    "First name" text,
    "Last name" text,
    "Gender" text,
    "Age" integer,
    "Junior" text,
    "Date of birth" text,
    "Membership" text,
    "Payment" text,
    "Cost" numeric,
    "Paid" numeric,
    "Paid Credit Card" numeric,
    "Paid Direct Debit" numeric,
    "Paid Cash" numeric,
    "Paid Cheque" numeric,
    "Paid Other" numeric,
    "Gift aid" text,
    "Status" text,
    "Start Date" text,
    "Expiry Date" text,
    "Email address" text,
    "Phone number" text,
    "Work number" text,
    "Mobile number" text,
    "Emergency contact name" text,
    "Emergency phone number" text,
    "Address 1" text,
    "Address 2" text,
    "Address 3" text,
    "Town" text,
    "County" text,
    "Country" text,
    "Postcode" text,
    "British Tennis Number" text,
    "Date joined venue" text,
    "Medical history" text,
    "Venue source" text,
    "Contact source" text,
    "Occupation" text,
    "Tags provided" text,
    "Key pin number" text,
    "Registered" text,
    "Member status" text,
    "Receipt of Emails" text,
    "Share Contact Detail" text,
    "Member's Directory" text,
    "Photography" text,
    " Venue source" character varying,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    is_current boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS raw_members_main_contacts_is_current_idx
    ON public.raw_members_main_contacts (is_current);

CREATE TABLE IF NOT EXISTS public.raw_members_main_contacts_import_staging (
    "Venue ID" text,
    "First name" text,
    "Last name" text,
    "Gender" text,
    "Age" integer,
    "Junior" text,
    "Date of birth" text,
    "Membership" text,
    "Payment" text,
    "Cost" numeric,
    "Paid" numeric,
    "Paid Credit Card" numeric,
    "Paid Direct Debit" numeric,
    "Paid Cash" numeric,
    "Paid Cheque" numeric,
    "Paid Other" numeric,
    "Gift aid" text,
    "Status" text,
    "Start Date" text,
    "Expiry Date" text,
    "Email address" text,
    "Phone number" text,
    "Work number" text,
    "Mobile number" text,
    "Emergency contact name" text,
    "Emergency phone number" text,
    "Address 1" text,
    "Address 2" text,
    "Address 3" text,
    "Town" text,
    "County" text,
    "Country" text,
    "Postcode" text,
    "British Tennis Number" text,
    "Date joined venue" text,
    "Medical history" text,
    "Venue source" text,
    "Contact source" text,
    "Occupation" text,
    "Tags provided" text,
    "Key pin number" text,
    "Registered" text,
    "Member status" text,
    "Receipt of Emails" text,
    "Share Contact Detail" text,
    "Member's Directory" text,
    "Photography" text,
    " Venue source" character varying
);

CREATE OR REPLACE FUNCTION public.prepare_raw_members_main_contacts_import_staging()
RETURNS integer
LANGUAGE plpgsql
AS $$
BEGIN
    TRUNCATE TABLE public.raw_members_main_contacts_import_staging;
    RETURN 1;
END;
$$;

CREATE OR REPLACE FUNCTION public.reconcile_raw_members_main_contacts_from_staging()
RETURNS TABLE(updated_count integer, inserted_count integer, deactivated_count integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_now timestamptz := now();
    v_updated integer := 0;
    v_inserted integer := 0;
    v_deactivated integer := 0;
BEGIN
    CREATE TEMP TABLE tmp_stage_raw_members_main_contacts ON COMMIT DROP AS
    SELECT
        row_number() OVER (
            ORDER BY
                COALESCE("Venue ID", ''),
                COALESCE("British Tennis Number", ''),
                COALESCE("First name", ''),
                COALESCE("Last name", ''),
                COALESCE("Membership", '')
        ) AS source_row,
        s.*,
        public.normalize_match_text(s."Venue ID") AS norm_venue_id,
        public.normalize_match_text(s."British Tennis Number") AS norm_btn,
        public.normalize_match_text(CONCAT_WS(' ', s."First name", s."Last name")) AS norm_name,
        public.normalize_membership_category(s."Membership") AS norm_category
    FROM public.raw_members_main_contacts_import_staging s;

    CREATE TEMP TABLE tmp_current_raw_members_main_contacts ON COMMIT DROP AS
    SELECT
        m.id,
        public.normalize_match_text(m."Venue ID") AS norm_venue_id,
        public.normalize_match_text(m."British Tennis Number") AS norm_btn,
        public.normalize_match_text(CONCAT_WS(' ', m."First name", m."Last name")) AS norm_name,
        public.normalize_membership_category(m."Membership") AS norm_category
    FROM public.raw_members_main_contacts m
    WHERE COALESCE(m.is_current, true) = true;

    CREATE TEMP TABLE tmp_matched_raw_members_main_contacts (
        source_row integer PRIMARY KEY,
        target_id bigint UNIQUE,
        match_rule text NOT NULL
    ) ON COMMIT DROP;

    INSERT INTO tmp_matched_raw_members_main_contacts (source_row, target_id, match_rule)
    WITH stage_ranked AS (
        SELECT
            source_row,
            norm_venue_id,
            row_number() OVER (
                PARTITION BY norm_venue_id
                ORDER BY source_row
            ) AS rn
        FROM tmp_stage_raw_members_main_contacts
        WHERE norm_venue_id IS NOT NULL
    ),
    current_ranked AS (
        SELECT
            id,
            norm_venue_id,
            row_number() OVER (
                PARTITION BY norm_venue_id
                ORDER BY id
            ) AS rn
        FROM tmp_current_raw_members_main_contacts
        WHERE norm_venue_id IS NOT NULL
    )
    SELECT
        s.source_row,
        c.id,
        'venue_id'
    FROM stage_ranked s
    JOIN current_ranked c
      ON c.norm_venue_id = s.norm_venue_id
     AND c.rn = s.rn;

    INSERT INTO tmp_matched_raw_members_main_contacts (source_row, target_id, match_rule)
    WITH stage_ranked AS (
        SELECT
            s.source_row,
            s.norm_btn,
            row_number() OVER (
                PARTITION BY s.norm_btn
                ORDER BY s.source_row
            ) AS rn
        FROM tmp_stage_raw_members_main_contacts s
        LEFT JOIN tmp_matched_raw_members_main_contacts m
          ON m.source_row = s.source_row
        WHERE m.source_row IS NULL
          AND s.norm_btn IS NOT NULL
    ),
    current_ranked AS (
        SELECT
            c.id,
            c.norm_btn,
            row_number() OVER (
                PARTITION BY c.norm_btn
                ORDER BY c.id
            ) AS rn
        FROM tmp_current_raw_members_main_contacts c
        LEFT JOIN tmp_matched_raw_members_main_contacts m
          ON m.target_id = c.id
        WHERE m.target_id IS NULL
          AND c.norm_btn IS NOT NULL
    )
    SELECT
        s.source_row,
        c.id,
        'british_tennis_number'
    FROM stage_ranked s
    JOIN current_ranked c
      ON c.norm_btn = s.norm_btn
     AND c.rn = s.rn;

    INSERT INTO tmp_matched_raw_members_main_contacts (source_row, target_id, match_rule)
    WITH stage_ranked AS (
        SELECT
            s.source_row,
            s.norm_name,
            s.norm_category,
            row_number() OVER (
                PARTITION BY s.norm_name, s.norm_category
                ORDER BY s.source_row
            ) AS rn
        FROM tmp_stage_raw_members_main_contacts s
        LEFT JOIN tmp_matched_raw_members_main_contacts m
          ON m.source_row = s.source_row
        WHERE m.source_row IS NULL
          AND s.norm_name IS NOT NULL
          AND s.norm_category IS NOT NULL
    ),
    current_ranked AS (
        SELECT
            c.id,
            c.norm_name,
            c.norm_category,
            row_number() OVER (
                PARTITION BY c.norm_name, c.norm_category
                ORDER BY c.id
            ) AS rn
        FROM tmp_current_raw_members_main_contacts c
        LEFT JOIN tmp_matched_raw_members_main_contacts m
          ON m.target_id = c.id
        WHERE m.target_id IS NULL
          AND c.norm_name IS NOT NULL
          AND c.norm_category IS NOT NULL
    )
    SELECT
        s.source_row,
        c.id,
        'name_category'
    FROM stage_ranked s
    JOIN current_ranked c
      ON c.norm_name = s.norm_name
     AND c.norm_category = s.norm_category
     AND c.rn = s.rn;

    UPDATE public.raw_members_main_contacts rm
    SET
        "Venue ID" = s."Venue ID",
        "First name" = s."First name",
        "Last name" = s."Last name",
        "Gender" = s."Gender",
        "Age" = s."Age",
        "Junior" = s."Junior",
        "Date of birth" = s."Date of birth",
        "Membership" = s."Membership",
        "Payment" = s."Payment",
        "Cost" = s."Cost",
        "Paid" = s."Paid",
        "Paid Credit Card" = s."Paid Credit Card",
        "Paid Direct Debit" = s."Paid Direct Debit",
        "Paid Cash" = s."Paid Cash",
        "Paid Cheque" = s."Paid Cheque",
        "Paid Other" = s."Paid Other",
        "Gift aid" = s."Gift aid",
        "Status" = s."Status",
        "Start Date" = s."Start Date",
        "Expiry Date" = s."Expiry Date",
        "Email address" = s."Email address",
        "Phone number" = s."Phone number",
        "Work number" = s."Work number",
        "Mobile number" = s."Mobile number",
        "Emergency contact name" = s."Emergency contact name",
        "Emergency phone number" = s."Emergency phone number",
        "Address 1" = s."Address 1",
        "Address 2" = s."Address 2",
        "Address 3" = s."Address 3",
        "Town" = s."Town",
        "County" = s."County",
        "Country" = s."Country",
        "Postcode" = s."Postcode",
        "British Tennis Number" = s."British Tennis Number",
        "Date joined venue" = s."Date joined venue",
        "Medical history" = s."Medical history",
        "Venue source" = s."Venue source",
        "Contact source" = s."Contact source",
        "Occupation" = s."Occupation",
        "Tags provided" = s."Tags provided",
        "Key pin number" = s."Key pin number",
        "Registered" = s."Registered",
        "Member status" = s."Member status",
        "Receipt of Emails" = s."Receipt of Emails",
        "Share Contact Detail" = s."Share Contact Detail",
        "Member's Directory" = s."Member's Directory",
        "Photography" = s."Photography",
        " Venue source" = s." Venue source",
        last_seen_at = v_now,
        is_current = true
    FROM tmp_matched_raw_members_main_contacts m
    JOIN tmp_stage_raw_members_main_contacts s
      ON s.source_row = m.source_row
    WHERE rm.id = m.target_id;
    GET DIAGNOSTICS v_updated = ROW_COUNT;

    INSERT INTO public.raw_members_main_contacts (
        "Venue ID",
        "First name",
        "Last name",
        "Gender",
        "Age",
        "Junior",
        "Date of birth",
        "Membership",
        "Payment",
        "Cost",
        "Paid",
        "Paid Credit Card",
        "Paid Direct Debit",
        "Paid Cash",
        "Paid Cheque",
        "Paid Other",
        "Gift aid",
        "Status",
        "Start Date",
        "Expiry Date",
        "Email address",
        "Phone number",
        "Work number",
        "Mobile number",
        "Emergency contact name",
        "Emergency phone number",
        "Address 1",
        "Address 2",
        "Address 3",
        "Town",
        "County",
        "Country",
        "Postcode",
        "British Tennis Number",
        "Date joined venue",
        "Medical history",
        "Venue source",
        "Contact source",
        "Occupation",
        "Tags provided",
        "Key pin number",
        "Registered",
        "Member status",
        "Receipt of Emails",
        "Share Contact Detail",
        "Member's Directory",
        "Photography",
        " Venue source",
        first_seen_at,
        last_seen_at,
        is_current
    )
    SELECT
        s."Venue ID",
        s."First name",
        s."Last name",
        s."Gender",
        s."Age",
        s."Junior",
        s."Date of birth",
        s."Membership",
        s."Payment",
        s."Cost",
        s."Paid",
        s."Paid Credit Card",
        s."Paid Direct Debit",
        s."Paid Cash",
        s."Paid Cheque",
        s."Paid Other",
        s."Gift aid",
        s."Status",
        s."Start Date",
        s."Expiry Date",
        s."Email address",
        s."Phone number",
        s."Work number",
        s."Mobile number",
        s."Emergency contact name",
        s."Emergency phone number",
        s."Address 1",
        s."Address 2",
        s."Address 3",
        s."Town",
        s."County",
        s."Country",
        s."Postcode",
        s."British Tennis Number",
        s."Date joined venue",
        s."Medical history",
        s."Venue source",
        s."Contact source",
        s."Occupation",
        s."Tags provided",
        s."Key pin number",
        s."Registered",
        s."Member status",
        s."Receipt of Emails",
        s."Share Contact Detail",
        s."Member's Directory",
        s."Photography",
        s." Venue source",
        v_now,
        v_now,
        true
    FROM tmp_stage_raw_members_main_contacts s
    LEFT JOIN tmp_matched_raw_members_main_contacts m
      ON m.source_row = s.source_row
    WHERE m.source_row IS NULL;
    GET DIAGNOSTICS v_inserted = ROW_COUNT;

    UPDATE public.raw_members_main_contacts rm
    SET is_current = false
    FROM tmp_current_raw_members_main_contacts c
    LEFT JOIN tmp_matched_raw_members_main_contacts m
      ON m.target_id = c.id
    WHERE rm.id = c.id
      AND m.target_id IS NULL
      AND COALESCE(rm.is_current, true) = true;
    GET DIAGNOSTICS v_deactivated = ROW_COUNT;

    RETURN QUERY SELECT v_updated, v_inserted, v_deactivated;
END;
$$;

CREATE OR REPLACE VIEW public.vw_raw_members_main_contacts_current AS
SELECT *
FROM public.raw_members_main_contacts
WHERE COALESCE(is_current, true) = true;

CREATE OR REPLACE VIEW public.vw_junior_main_contacts AS
WITH junior_members AS (
    SELECT
        rm.id AS member_raw_id,
        trim(concat_ws(' ', rm."First name", rm."Last name")) AS member_name,
        NULLIF(trim(rm."First name"), '') AS member_first_name,
        NULLIF(trim(rm."Last name"), '') AS member_last_name,
        NULLIF(trim(rm."Email address"), '') AS member_email,
        rm."Membership" AS membership,
        rm."Status" AS status,
        rm."Payment" AS payment,
        rm."Paid" AS paid_total,
        rm."Start Date" AS start_date,
        rm."Expiry Date" AS expiry_date,
        rm."Venue ID" AS venue_id,
        rm."British Tennis Number" AS british_tennis_number,
        rm."Address 1" AS member_address_1,
        rm."Postcode" AS member_postcode,
        public.normalize_match_text(concat_ws(' ', rm."First name", rm."Last name")) AS norm_member_name,
        public.normalize_match_text(rm."Last name") AS norm_member_last_name,
        NULLIF(substring(rm."Membership" FROM '(20[0-9]{2})'), '') AS season
    FROM public.raw_members rm
    WHERE COALESCE(rm.is_current, true) = true
      AND COALESCE(NULLIF(trim(rm."Junior"), ''), 'No') = 'Yes'
),
main_contact_rows AS (
    SELECT
        mc.id AS main_contact_raw_id,
        trim(concat_ws(' ', mc."First name", mc."Last name")) AS main_contact_name,
        NULLIF(trim(mc."First name"), '') AS main_contact_first_name,
        NULLIF(trim(mc."Last name"), '') AS main_contact_last_name,
        NULLIF(trim(mc."Email address"), '') AS main_contact_email,
        NULLIF(trim(mc."Phone number"), '') AS main_contact_phone,
        NULLIF(trim(mc."Mobile number"), '') AS main_contact_mobile,
        NULLIF(trim(mc."Address 1"), '') AS main_contact_address_1,
        NULLIF(trim(mc."Address 2"), '') AS main_contact_address_2,
        NULLIF(trim(mc."Address 3"), '') AS main_contact_address_3,
        NULLIF(trim(mc."Town"), '') AS main_contact_town,
        NULLIF(trim(mc."County"), '') AS main_contact_county,
        NULLIF(trim(mc."Postcode"), '') AS main_contact_postcode,
        mc."Membership" AS membership,
        mc."Status" AS status,
        mc."Payment" AS payment,
        mc."Paid" AS paid_total,
        mc."Start Date" AS start_date,
        mc."Expiry Date" AS expiry_date,
        public.normalize_match_text(concat_ws(' ', mc."First name", mc."Last name")) AS norm_main_contact_name,
        public.normalize_match_text(mc."Last name") AS norm_main_contact_last_name,
        public.normalize_match_email(mc."Email address") AS norm_main_contact_email
    FROM public.raw_members_main_contacts mc
    WHERE COALESCE(mc.is_current, true) = true
),
candidate_rows AS (
    SELECT
        jm.member_raw_id,
        jm.member_name,
        jm.member_first_name,
        jm.member_last_name,
        jm.member_email,
        jm.membership,
        jm.status,
        jm.payment,
        jm.paid_total,
        jm.start_date,
        jm.expiry_date,
        jm.venue_id,
        jm.british_tennis_number,
        jm.member_address_1,
        jm.member_postcode,
        jm.season,
        mc.main_contact_raw_id,
        mc.main_contact_name,
        mc.main_contact_first_name,
        mc.main_contact_last_name,
        mc.main_contact_email,
        mc.main_contact_phone,
        mc.main_contact_mobile,
        mc.main_contact_address_1,
        mc.main_contact_address_2,
        mc.main_contact_address_3,
        mc.main_contact_town,
        mc.main_contact_county,
        mc.main_contact_postcode,
        mc.norm_main_contact_name,
        mc.norm_main_contact_email,
        row_number() OVER (
            PARTITION BY
                jm.member_raw_id,
                mc.norm_main_contact_name,
                COALESCE(mc.norm_main_contact_email, '')
            ORDER BY mc.main_contact_raw_id
        ) AS duplicate_rank
    FROM junior_members jm
    JOIN main_contact_rows mc
      ON COALESCE(jm.membership, '') = COALESCE(mc.membership, '')
     AND COALESCE(jm.status, '') = COALESCE(mc.status, '')
     AND COALESCE(jm.payment, '') = COALESCE(mc.payment, '')
     AND COALESCE(jm.start_date, '') = COALESCE(mc.start_date, '')
     AND COALESCE(jm.expiry_date, '') = COALESCE(mc.expiry_date, '')
     AND COALESCE(jm.paid_total, -1) = COALESCE(mc.paid_total, -1)
     AND jm.norm_member_last_name = mc.norm_main_contact_last_name
     AND jm.norm_member_name <> mc.norm_main_contact_name
),
candidate_identities AS (
    SELECT *
    FROM candidate_rows
    WHERE duplicate_rank = 1
),
candidate_counts AS (
    SELECT
        member_raw_id,
        count(*)::integer AS candidate_count
    FROM candidate_identities
    GROUP BY member_raw_id
),
ranked_candidates AS (
    SELECT
        ci.*,
        row_number() OVER (
            PARTITION BY ci.member_raw_id
            ORDER BY
                CASE WHEN ci.main_contact_email IS NOT NULL THEN 0 ELSE 1 END,
                CASE WHEN COALESCE(ci.main_contact_mobile, ci.main_contact_phone) IS NOT NULL THEN 0 ELSE 1 END,
                CASE WHEN COALESCE(ci.main_contact_address_1, ci.main_contact_postcode) IS NOT NULL THEN 0 ELSE 1 END,
                ci.main_contact_name,
                ci.main_contact_raw_id
        ) AS candidate_rank
    FROM candidate_identities ci
)
SELECT
    jm.member_raw_id,
    jm.member_name,
    jm.member_first_name,
    jm.member_last_name,
    jm.member_email,
    jm.membership,
    jm.season,
    jm.status,
    jm.payment,
    jm.start_date,
    jm.expiry_date,
    rc.main_contact_raw_id,
    rc.main_contact_name,
    rc.main_contact_first_name,
    rc.main_contact_last_name,
    COALESCE(bc.email_address, rc.main_contact_email) AS main_contact_email,
    COALESCE(NULLIF(trim(bc.mobile_number), ''), rc.main_contact_mobile) AS main_contact_mobile,
    COALESCE(NULLIF(trim(bc.phone_number), ''), rc.main_contact_phone) AS main_contact_phone,
    COALESCE(NULLIF(trim(bc.address_1), ''), rc.main_contact_address_1) AS main_contact_address_1,
    COALESCE(NULLIF(trim(bc.address_2), ''), rc.main_contact_address_2) AS main_contact_address_2,
    COALESCE(NULLIF(trim(bc.address_3), ''), rc.main_contact_address_3) AS main_contact_address_3,
    COALESCE(NULLIF(trim(bc.town), ''), rc.main_contact_town) AS main_contact_town,
    COALESCE(NULLIF(trim(bc.county), ''), rc.main_contact_county) AS main_contact_county,
    COALESCE(NULLIF(trim(bc.postcode), ''), rc.main_contact_postcode) AS main_contact_postcode,
    bc.contact_id AS resolved_contact_id,
    bc.resolve_rule AS resolved_contact_rule,
    COALESCE(cc.candidate_count, 0) AS candidate_count,
    CASE
        WHEN COALESCE(cc.candidate_count, 0) = 1 THEN 'high'
        WHEN COALESCE(cc.candidate_count, 0) > 1 THEN 'ambiguous'
        ELSE 'unresolved'
    END AS match_confidence,
    CASE
        WHEN COALESCE(cc.candidate_count, 0) = 1 THEN 'direct_main_contacts_export_same_surname'
        WHEN COALESCE(cc.candidate_count, 0) > 1 THEN 'ambiguous_main_contacts_export_same_surname'
        ELSE 'unresolved'
    END AS match_rule
FROM junior_members jm
LEFT JOIN candidate_counts cc
  ON cc.member_raw_id = jm.member_raw_id
LEFT JOIN ranked_candidates rc
  ON rc.member_raw_id = jm.member_raw_id
 AND rc.candidate_rank = 1
LEFT JOIN LATERAL public.resolve_best_contact_row(
    rc.main_contact_name,
    rc.main_contact_email,
    NULLIF(regexp_replace(rc.main_contact_name, '^\S+\s*', ''), ''),
    false
) bc
  ON COALESCE(cc.candidate_count, 0) = 1
 AND rc.main_contact_name IS NOT NULL;

CREATE OR REPLACE FUNCTION public.run_main_contacts_resolution_regression_checks()
RETURNS TABLE (
    check_name text,
    ok boolean,
    expected text,
    actual text
)
LANGUAGE sql
STABLE
AS $$
    WITH checks AS (
        SELECT
            'antonios_nicolaidis_resolves_to_george_nicolaidis'::text AS check_name,
            (
                j.main_contact_name = 'George Nicolaidis'
                AND j.match_rule = 'direct_main_contacts_export_same_surname'
                AND j.candidate_count = 1
            ) AS ok,
            'main_contact_name=George Nicolaidis match_rule=direct_main_contacts_export_same_surname candidate_count=1'::text AS expected,
            format(
                'main_contact_name=%s match_rule=%s candidate_count=%s',
                COALESCE(j.main_contact_name, 'NULL'),
                COALESCE(j.match_rule, 'NULL'),
                COALESCE(j.candidate_count::text, 'NULL')
            ) AS actual
        FROM public.vw_junior_main_contacts j
        WHERE j.member_name = 'Antonios Nicolaidis'

        UNION ALL

        SELECT
            'gerasimos_nicolaidis_resolves_to_george_nicolaidis',
            (
                j.main_contact_name = 'George Nicolaidis'
                AND j.match_rule = 'direct_main_contacts_export_same_surname'
                AND j.candidate_count = 1
            ) AS ok,
            'main_contact_name=George Nicolaidis match_rule=direct_main_contacts_export_same_surname candidate_count=1',
            format(
                'main_contact_name=%s match_rule=%s candidate_count=%s',
                COALESCE(j.main_contact_name, 'NULL'),
                COALESCE(j.match_rule, 'NULL'),
                COALESCE(j.candidate_count::text, 'NULL')
            )
        FROM public.vw_junior_main_contacts j
        WHERE j.member_name = 'Gerasimos Nicolaidis'
    )
    SELECT check_name, ok, expected, actual
    FROM checks
    ORDER BY check_name;
$$;

CREATE OR REPLACE VIEW public.vw_main_contacts_resolution_regression_checks AS
SELECT *
FROM public.run_main_contacts_resolution_regression_checks();

COMMIT;
