BEGIN;

CREATE TABLE IF NOT EXISTS public.teams (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_source text,
    section text,
    team_name text NOT NULL,
    season text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.team_players (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id bigint NOT NULL REFERENCES public.teams(id) ON DELETE CASCADE,
    source_name text NOT NULL,
    is_captain boolean NOT NULL DEFAULT false,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.team_name_overrides (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source text NOT NULL,
    target text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source, target)
);

CREATE INDEX IF NOT EXISTS idx_teams_season ON public.teams(season);
CREATE INDEX IF NOT EXISTS idx_team_players_team_id ON public.team_players(team_id);
CREATE INDEX IF NOT EXISTS idx_team_name_overrides_source ON public.team_name_overrides(source);

COMMIT;
