INSERT INTO public.team_name_overrides (source, target) VALUES
('Jax', 'Jacqueline'),
('Jacqui', 'Jacqueline'),
('Jacquie', 'Jacqueline'),
('Jackie', 'Jacqueline'),
('Dave', 'David'),
('Andy', 'Andrew'),
('Alec', 'Alexander'),
('Alec', 'Aleksander'),
('Alex', 'Alexander'),
('Alex', 'Aleksander'),
('Alistair', 'Alistair'),
('Becky', 'Rebecca'),
('Carole', 'Carol'),
('Chris', 'Christopher'),
('Graeme', 'Graham'),
('Jo', 'Joanne'),
('Jon', 'John'),
('Jon', 'Jonathan'),
('Kat', 'Katherine'),
('Kate', 'Katherine'),
('Katharine', 'Katherine'),
('Kathryn', 'Katherine'),
('Catherine', 'Katherine'),
('Liz', 'Elizabeth'),
('Liza', 'Elizabeth'),
('Lynn', 'Lynne'),
('Maew', 'Mae'),
('Matt', 'Matthew'),
('Mike', 'Michael'),
('Mo', 'Maureen'),
('Pete', 'Peter'),
('Roni', 'Ronnie'),
('Ronnie', 'Veronica'),
('Sam', 'Samuel'),
('Sam', 'Samantha'),
('Sue', 'Susan'),
('Susie', 'Susan'),
('Suzanne', 'Susan'),
('Tim', 'Timothy'),
('Tom', 'Thomas'),
('Trish', 'Patricia'),
('Val', 'Valerie'),
('Vicky', 'Victoria'),
('Vicki', 'Victoria'),
('Tom Van Klavern', 'Thomas Van Klaveren'),
('Jane Woods', 'Alison Woods'),
('JANE DOW', 'Jane Timmis'),
('JAX S BROWN', 'Jacqueline Sinclair-Brown'),
('Jax S B', 'Jacqueline Sinclair-Brown'),
('Carol Ann Harrison', 'Carol-Anne Harrison'),
('CAROLE -ANN HARRISON', 'Carol-Anne Harrison')
ON CONFLICT (source, target) DO NOTHING;
